import bookmark from '../assets/icons/bookmark.png';
import eye_hide from '../assets/icons/eye-hide.png';
import eye from '../assets/icons/eye.png';
import left_arrow from '../assets/icons/left-arrow.png';
import logout from '../assets/icons/logout.png';
import menu from '../assets/icons/menu.png';
import play from '../assets/icons/play.png';
import plus from '../assets/icons/plus.png';
import right_arrow from '../assets/icons/right-arrow.png';
import search from '../assets/icons/search.png';
import settings from '../assets/icons/settings.png';
import upload from '../assets/icons/upload.png';
import home from '../assets/icons/home.png';
import profile from '../assets/icons/profile.png';
import retweet from '../assets/icons/retweet.png';
import comment from '../assets/icons/comment.png';
import likes_filled from '../assets/icons/likes-filled.png';
import share from '../assets/icons/share.png';

export default  {bookmark, eye_hide, eye, left_arrow, logout, menu, play, plus, right_arrow, search, settings, upload, home, profile, retweet, comment, likes_filled, share};